# Generated by Django 4.2.6 on 2023-10-12 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UpgradeLevel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('benefit', models.CharField(max_length=100)),
                ('requirement', models.CharField(max_length=100)),
                ('cost', models.IntegerField()),
                ('time', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('can_attack', models.CharField(max_length=200)),
                ('damage', models.IntegerField()),
                ('range', models.IntegerField()),
                ('accuracy_moving', models.FloatField()),
                ('accuracy_stationary', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UnitUpgrade1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('total_levels', models.IntegerField()),
                ('levels', models.ManyToManyField(to='awiki.upgradelevel1')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=20)),
                ('unit_faction', models.CharField(max_length=20)),
                ('category', models.CharField(default='?', max_length=25)),
                ('unit_type', models.CharField(default='?', max_length=20)),
                ('unit_trained_in', models.CharField(default='?', max_length=50)),
                ('unit_discription', models.CharField(default='?', max_length=500)),
                ('unit_discription2', models.CharField(default='?', max_length=500)),
                ('image', models.ImageField(default='', upload_to='awiki/images')),
                ('avialable_from_rank', models.CharField(default='?', max_length=2)),
                ('stat_hp', models.CharField(default='?', max_length=7)),
                ('stat_armor', models.CharField(default='?', max_length=3)),
                ('stat_armor_type', models.CharField(default='?', max_length=1)),
                ('stat_speed', models.CharField(default='?', max_length=5)),
                ('stat_view', models.CharField(default='?', max_length=7)),
                ('stat_cost', models.CharField(default='?', max_length=7)),
                ('stat_time', models.CharField(default='?', max_length=7)),
                ('stat_cp', models.CharField(default='?', max_length=7)),
                ('primary_weapon', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_weapon', to='awiki.weapon')),
                ('secondary_weapon', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_weapon', to='awiki.weapon')),
                ('upgrades', models.ManyToManyField(to='awiki.unitupgrade1')),
            ],
        ),
    ]
