# Generated by Django 4.2.6 on 2023-10-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upgradelevel1',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
