# Generated by Django 4.2.6 on 2023-10-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awiki', '0002_alter_upgradelevel1_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgradelevel1',
            name='upgrade_name',
            field=models.CharField(default='?', max_length=100),
        ),
        migrations.AlterField(
            model_name='upgradelevel1',
            name='benefit',
            field=models.CharField(default='?', max_length=100),
        ),
        migrations.AlterField(
            model_name='upgradelevel1',
            name='cost',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='upgradelevel1',
            name='requirement',
            field=models.CharField(default='?', max_length=100),
        ),
        migrations.AlterField(
            model_name='upgradelevel1',
            name='time',
            field=models.CharField(default='?', max_length=100),
        ),
    ]
