# Generated by Django 4.2.6 on 2023-10-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awiki', '0003_upgradelevel1_upgrade_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapon',
            name='damage',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='range',
        ),
        migrations.AddField(
            model_name='weapon',
            name='damage1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weapon',
            name='damage2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weapon',
            name='damage3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weapon',
            name='explosive_radius',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='weapon',
            name='firing_range',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='accuracy_moving',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='accuracy_stationary',
            field=models.FloatField(default=0),
        ),
    ]
