# Generated by Django 4.2.6 on 2023-10-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awiki', '0004_remove_weapon_damage_remove_weapon_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitupgrade1',
            name='unit_name',
            field=models.CharField(default='?', max_length=50),
        ),
    ]
