# Generated by Django 4.2.6 on 2023-10-13 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awiki', '0005_unitupgrade1_unit_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upgradelevel1',
            name='benefit',
            field=models.CharField(default='?', max_length=300),
        ),
    ]
